### ISSUE TITLE
Does not like not setting proxy.

### ISSUE THREAD

**Issue by cheako** [tom-doerr/chatgpt_commit_message_hook#5]
The config file was just 3 lines, not 4 like the example.

```text
cheako@mx1:~/src/gitlab/hazel-rs$ git commit -a
Traceback (most recent call last):
  File "/usr/bin/prepare-commit-msg", line 161, in <module>
    api_key, proxy, max_changed_lines = initialize_openai_api()
                                        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/prepare-commit-msg", line 149, in initialize_openai_api
    proxy = config["openai"]["proxy"].strip('"').strip("'")
            ~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/usr/local/lib/python3.11/configparser.py", line 1273, in __getitem__
    raise KeyError(key)
KeyError: 'proxy'
```

**Comment by cheako** [comment]
Using `"prixy=\n"` worked.

**Comment by tom-doerr** [comment]
"prixy=\n" or "proxy=\n"?

**Comment by cheako** [comment]
That's an uninteresting distinction for me, I feel that unknown config options should warn over panic.  To answer your question "the latter," I made a typo in the issue comment.
