### ISSUE TITLE
ValueError: SHA could not be resolved

### ISSUE THREAD

**Issue by cheako** [tom-doerr/chatgpt_commit_message_hook#6]
I do not know why I'm getting this.

```text
cheako@mx1:~/src/gitlab/hazel-rs$ git commit -a
Traceback (most recent call last):
  File "/usr/bin/prepare-commit-msg", line 162, in <module>
    changes_dict = count_staged_changes()
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/prepare-commit-msg", line 36, in count_staged_changes
    staged_diff = index.diff("HEAD", create_patch=True, R=True)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/git/index/base.py", line 1386, in diff
    other = self.repo.rev_parse(other)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/git/repo/fun.py", line 378, in rev_parse
    obj = cast(Commit_ish, name_to_object(repo, rev))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/git/repo/fun.py", line 187, in name_to_object
    return Object.new_from_sha(repo, hex_to_bin(hexsha))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/git/objects/base.py", line 94, in new_from_sha
    oinfo = repo.odb.info(sha1)
            ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/git/db.py", line 40, in info
    hexsha, typename, size = self._git.get_object_header(bin_to_hex(binsha))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/git/cmd.py", line 1383, in get_object_header
    return self.__get_object_header(cmd, ref)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/git/cmd.py", line 1370, in __get_object_header
    return self._parse_object_header(cmd.stdout.readline())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/git/cmd.py", line 1329, in _parse_object_header
    raise ValueError("SHA could not be resolved, git returned: %r" % (header_line.strip()))
ValueError: SHA could not be resolved, git returned: b''
cheako@mx1:~/src/gitlab/hazel-rs$ git commit
Traceback (most recent call last):
  File "/usr/bin/prepare-commit-msg", line 162, in <module>
    changes_dict = count_staged_changes()
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/prepare-commit-msg", line 36, in count_staged_changes
    staged_diff = index.diff("HEAD", create_patch=True, R=True)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/git/index/base.py", line 1386, in diff
    other = self.repo.rev_parse(other)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/git/repo/fun.py", line 378, in rev_parse
    obj = cast(Commit_ish, name_to_object(repo, rev))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/git/repo/fun.py", line 187, in name_to_object
    return Object.new_from_sha(repo, hex_to_bin(hexsha))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/git/objects/base.py", line 94, in new_from_sha
    oinfo = repo.odb.info(sha1)
            ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/git/db.py", line 40, in info
    hexsha, typename, size = self._git.get_object_header(bin_to_hex(binsha))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/git/cmd.py", line 1383, in get_object_header
    return self.__get_object_header(cmd, ref)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/git/cmd.py", line 1370, in __get_object_header
    return self._parse_object_header(cmd.stdout.readline())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/git/cmd.py", line 1329, in _parse_object_header
    raise ValueError("SHA could not be resolved, git returned: %r" % (header_line.strip()))
ValueError: SHA could not be resolved, git returned: b''
```

**Comment by cheako** [comment]
This is git trying to enforce a security policy.
